cc_binary(
  name = 'chat_client',
  warning = 'no',
  extra_cppflags = '-std=c++0x',
  srcs = [
    'chat_client.cpp',
  ],
  deps = '//thirdparty/boost:boost',
)

cc_binary(
  name = 'chat_server',
  warning = 'no',
  extra_cppflags = '-std=c++0x',
  srcs = [
    'chat_server.cpp',
  ],
  deps = '//thirdparty/boost:boost',
)

cc_binary(
  name = 'posix_chat_client',
  warning = 'no',
  extra_cppflags = '-std=c++0x',
  srcs = [
    'posix_chat_client.cpp',
  ],
  deps = '//thirdparty/boost:boost',
)

