cc_library(
    name = 'libthrift',
    deps = [
        '//thirdparty/thrift-0.9.1:libthrift'
    ]
)

cc_library(
    name = 'libthriftnb',
    deps = [
        '//thirdparty/thrift-0.9.1:libthriftnb'
    ]
)

cc_library(
    name = 'libthriftz',
    deps = [
        '//thirdparty/thrift-0.9.1:libthriftz'
    ]
)

cc_binary(
    name = 'thriftc',
    deps = [
        '//thirdparty/thrift-0.9.1:libthriftc'
    ]
)
