cc_library(
    name = 'boost',
    deps = [
        ':chrono',
        ':cpp-netlib',
        ':filesystem',
        ':iostreams',
        ':regex',
        ':system',
        ':thread',
    ]
)

cc_library(
    name = 'chrono',
    deps = [
        '//thirdparty/boost_1_55_0:chrono'
    ]
)

cc_library(
    name = 'cpp-netlib',
    deps = [
        '//thirdparty/cpp-netlib-0.11.0-final:cpp-netlib'
    ]
)

cc_library(
    name = 'filesystem',
    deps = [
        '//thirdparty/boost_1_55_0:filesystem'
    ]
)

cc_library(
    name = 'iostreams',
    deps = [
        '//thirdparty/boost_1_55_0:iostreams'
    ]
)

cc_library(
    name = 'python',
    deps = [
        '//thirdparty/boost_1_55_0:python'
    ]
)

cc_library(
    name = 'regex',
    deps = [
        '//thirdparty/boost_1_55_0:regex'
    ]
)

cc_library(
    name = 'system',
    deps = [
        '//thirdparty/boost_1_55_0:system'
    ]
)

cc_library(
    name = 'thread',
    deps = [
        '//thirdparty/boost_1_55_0:thread'
    ]
)
