cc_library(
    name = 'boost',
    deps = [
        '//thirdparty/boost_1_54_0:regex'
    ]
)

cc_library(
    name = 'system',
    deps = [
        '//thirdparty/boost_1_54_0:system'
    ]
)

cc_library(
    name = 'thread',
    deps = [
        '//thirdparty/boost_1_54_0:thread'
    ]
)
