cc_library(
  name = 'boost',
  deps = [
    ':chrono',
    ':cpp-netlib',
    ':filesystem',
    ':iostreams',
    ':regex',
    ':system',
    ':thread',
  ]
)

cc_library(
  name = 'chrono',
  deps = [
    '//boost:chrono'
  ]
)

cc_library(
  name = 'cpp-netlib',
  deps = [
    '//thirdparty/cpp-netlib-0.11.0-final:cpp-netlib'
  ]
)

cc_library(
  name = 'filesystem',
  deps = [
    '//boost:filesystem'
  ]
)

cc_library(
  name = 'iostreams',
  deps = [
    '//boost:iostreams'
  ]
)

cc_library(
  name = 'python',
  deps = [
    '//boost:python'
  ]
)

cc_library(
  name = 'regex',
  deps = [
    '//boost:regex'
  ]
)

cc_library(
  name = 'system',
  deps = [
    '//boost:system'
  ]
)

cc_library(
  name = 'thread',
  deps = [
    '//boost:thread'
  ]
)
