cc_library(name = 'arena',
           deps = ['//thirdparty/re2-20140111/util:arena']
           )

cc_library(name = 'utf',
           deps = ['//thirdparty/re2-20140111/util:utf']
           )

cc_library(name = 'pcre',
           deps = ['//thirdparty/re2-20140111/util:pcre']
           )

cc_library(name = 'random',
           deps = ['//thirdparty/re2-20140111/util:random']
           )

cc_library(name = 'mini_test',
           deps = ['//thirdparty/re2-20140111/util:mini_test']
           )

cc_library(name = 'string_util',
           deps = ['//thirdparty/re2-20140111/util:string_util']
           )

cc_library(name = 'util',
           deps = ['//thirdparty/re2-20140111/util:util']
           )